name: hmmrnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.19.0
  - pytorch>=1.7.0
  - matplotlib>=3.3.0
  - scikit-learn>=0.24.0
  - ipykernel>=6.0.0
  - jupyter>=1.0.0
  - pip>=20.0
  - pip:
    - hmmlearn>=0.2.5
    - geomloss>=0.2.3
    - plotly>=4.14.0
    - seaborn>=0.11.0
    - tqdm>=4.50.0
